### ISSUE TITLE
Student unable to log into any jupyter labs

### ISSUE THREAD

**Issue by solomonlr** [2i2c-org/pilot#57] opened 2021-03-10 20:36 UTC
A student Safelg (email: safelg_preciado@elcamino.edu) in the El Camino 2i2c site keeps getting a 500: Internal Server Error.

I tried stopping and restarting his server and had him log out of all his google accounts. I then accessed his server and received the same error message.  I can't figure out what's wrong.

-------------------------------------------- 

Thanks for reporting your issue! Sorry things aren't working as expected.

In order to help resolve things quickly, please provide the following information:

✔️ The URL of your hub:
hhttps://elcamino.cloudbank.2i2c.cloud/user/safelg_preciado@elcamino.edu/notebooks/ecc-materials-sp2021/materials/x19/lab/1/lab01/lab01.ipynb
✔️ What you expected to happen:
notebook to oepn
✔️ What actually happened:
500: Internal Server Error
✔️ Any error messages you see:
above
✔️ Any specific packages or tools you were using:
N/A

**Comment by yuvipanda** [comment] 2021-03-10 21:53
heya! I'm investigating, should have something soon :)

**Comment by yuvipanda** [comment] 2021-03-10 21:58
Looks like the student had somehow accidentally installed a custom verison of nbconvert in their home directory. It was in `.local/lib/python3.8/site-packages/`. I moved that so the version of nbconvert is back to what we ship, and it works now!

This is probably caused by running `pip install --user <some-package>`. While it works in many cases, sometimes it causes an incompatibility and causes hard to debug issues like this. I saw this by accessing their server, creating a terminal (New -> Terminal), and then looking inside `.local/lib/python3.8`.

It works for me now! Can you try it out and let me know if it works for you too?

**Comment by yuvipanda** [comment] 2021-03-10 22:01
I also saw this error message while looking at the notebook logs:

```
[W 2021-03-10 21:52:40.771 SingleUserNotebookApp configurable:168] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-03-10 21:52:40.785 SingleUserNotebookApp configurable:168] Config option `template_path` not recognized by `ExporterCollapsibleHeadings`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-03-10 21:52:40.870 SingleUserNotebookApp configurable:168] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-03-10 21:52:40.881 SingleUserNotebookApp configurable:168] Config option `template_path` not recognized by `TocExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-03-10 21:52:40.899 SingleUserNotebookApp configurable:168] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-03-10 21:52:40.911 SingleUserNotebookApp configurable:168] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-03-10 21:52:40.966 SingleUserNotebookApp configurable:168] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 2021-03-10 21:52:40.984 SingleUserNotebookApp configurable:168] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[E 2021-03-10 21:52:41.010 SingleUserNotebookApp web:1789] Uncaught exception GET /user/safelg_preciado@elcamino.edu/notebooks/ecc-materials-sp2021/materials/x19/lab/1/lab01/lab01.ipynb (10.128.0.19)
    HTTPServerRequest(protocol='https', host='elcamino.cloudbank.2i2c.cloud', method='GET', uri='/user/safelg_preciado@elcamino.edu/notebooks/ecc-materials-sp2021/materials/x19/lab/1/lab01/lab01.ipynb', version='HTTP/1.1', remote_ip='10.128.0.19')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 775, in run
        yielded = self.gen.send(value)
      File "/opt/conda/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "/opt/conda/lib/python3.8/site-packages/notebook/base/handlers.py", line 512, in render_template
        return template.render(**ns)
      File "/opt/conda/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/opt/conda/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/opt/conda/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/opt/conda/lib/python3.8/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "<template>", line 2, in top-level template code
      File "/opt/conda/lib/python3.8/site-packages/notebook/templates/page.html"
, line 154, in top-level template code
        {% block header %}
      File "/opt/conda/lib/python3.8/site-packages/notebook/templates/notebook.h
tml", line 115, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/opt/conda/lib/python3.8/site-packages/notebook/notebook/handlers.py
", line 40, in get_frontend_exporters
        for name in get_export_names():
      File "/home/jovyan/.local/lib/python3.8/site-packages/nbconvert/exporters/
base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/home/jovyan/.local/lib/python3.8/site-packages/nbconvert/exporters/
base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/opt/conda/lib/python3.8/site-packages/nbinteract/exporters.py", lin
e 125, in __init__
        self.template_path.insert(
    AttributeError: 'InteractExporter' object has no attribute 'template_path'
[E 2021-03-10 21:52:41.013 SingleUserNotebookApp log:166] {
```

Points to probably an issue with https://www.nbinteract.com/, which I think isn't widely used either.

**Comment by choldgraf** [comment] 2021-03-10 22:17
I think that this one is now resolved, so gonna close it! @solomonlr please feel free to ping again or re-open if it still doesn't work.

**Comment by solomonlr** [comment] 2021-03-10 22:18
Yes, this looks good, thanks so much!

**Comment by choldgraf** [comment] 2021-03-10 22:20
Also opened up https://github.com/2i2c-org/pilot/issues/58 to track documenting challenges w/ user installs!

**Closed** 2021-03-16 20:47 UTC
Labels: bug
